[theme]
base = "light"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#111111"
primaryColor = "#111111"
font = "sans serif"

[server]
headless = true

[client]
showErrorDetails = true

[runner]
fastReruns = true
