[server]
headless = true
address = "0.0.0.0"
port = 8099
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#111111"
textColor = "#f5f5f5"
primaryColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
